{% set name = "pip-upgrader" %}
{% set version = "1.4.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pip_upgrader/pip_upgrader-{{ version }}.tar.gz
  sha256: ec07b93e06825d9cf40f475a8e021fc9d288446b479b40cb9aba406a6db65347

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - pip
    - colorclass
    - docopt
    - packaging
    - requests
    - terminaltables

test:
  commands:
    - pip-upgrade --help

about:
  home: https://github.com/simion/pip-upgrader
  license: Apache-2.0
  license_family: Apache
  # https://github.com/simion/pip-upgrader/pull/13
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'An interactive pip requirements upgrader. It also updates the version in your requirements.txt file.'
  description: |
    An interactive pip requirements upgrader. Because upgrading requirements,
    package by package, is a pain in the ass. It also updates the version in
    your requirements.txt file.
  doc_url: https://github.com/simion/pip-upgrader
  dev_url: https://github.com/simion/pip-upgrader

extra:
  recipe-maintainers:
    - djsutherland
