travis:
  secure:
    BINSTAR_TOKEN: JcBRnTBmyj7QZFIEREX5llnfYXmCOdYLF0QUkbbs1auStu5H+y7VArcHKYcfRIbsy7+KT7AM9EBLX9s72h+GIUHV0IJK9BLu3a8DBpesTQZ/sS83NZVJL0cdQLvOcAuRqC2lyOlySgBwGjSnZeDHCS+hdUyNJVyeDtJ6tp0m7c3lHzaI/NejbEKUPqTZTf5igAR/6NaCFgcrMrpRO0lqtIxclEUbdMmr8AuuKL0/4uLUsZF/ahMFiRRoWPNddUmz4MF4slmy99eqiqK3rMCdASDZJpVJZq0+jgkRF+hcWo+niw1BoMtziGo0mm2YhzorIgQGTfV6z7AUX4/ehgIbG6zf1aRxH+MmK4zcAEib6CSFEpZZ5hOdDifcO178ONn7bWa/oqoo1QXYq2rpnqQc6sxTRwi8rc6Gt+F35Vd8C1auag2npXvJEm36jZudvco33bPu/nsPJDj/kj2jPrdYvMv/YpL0tzRUEC3EtqUW4IWO6VhGQtAjXaNKGanJ1axgg2TgOwvT69XSOAOmCXNvWEwUOmTRuULO7ALnSDBp8VzBL+Kg5aC8IRFQw9P1dGySkNjP6UAvodI0YHlA0WteGW39Lz+rh59nh1tfC9FQAGhf9uXwD1Di5QUBF5UvBU0hKqkOj+igiux3R7IBlfj7lY9qSI22RXOpHA5S+bi6wrI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
